import {CardColorId} from '../types/joke';

const COLORS: CardColorId[] = [
  'teal',
  'purple',
  'red',
  'yellow',
  'blue',
  'orange',
];

export type FriendPhrase = {
  id: string;
  text: string;
  color: CardColorId;
};

const PHRASE_TEXTS = [
  'Suspicious sandwich',
  'Angry toaster',
  'Invisible socks',
  'Dramatic banana',
  'Lost Wi-Fi',
  'Tiny disaster',
  'Fancy potato',
  'Confused robot',
  'Lazy superhero',
  'Broken alarm',
  'Secret pizza',
  'Dancing fridge',
  'Serious duck',
  'Awkward silence',
  'Magic homework',
  'Crying cactus',
  'Running pillow',
  'Sleepy dragon',
  'Fake genius',
  'Panic button',
  'Bathroom meeting',
  'Forbidden snack',
  'Grandma’s password',
  'Emotional damage',
  'Office ghost',
  'Late excuse',
  'Wrong planet',
  'Party noodle',
  'Invisible chair',
  'Cheese emergency',
  'Drama llama',
  'Broken mirror',
  'Sneaky spoon',
  'Confetti problem',
  'Alien haircut',
  'Mystery smell',
  'Keyboard warrior',
  'Budget wizard',
  'Angry cupcake',
  'Tiny boss',
  'Fake meeting',
  'Sleepy detective',
  'Stolen sandwich',
  'Chaotic penguin',
  'Royal mistake',
  'Silent karaoke',
  'Pizza logic',
  'Suspicious grandma',
  'Dramatic entrance',
  'Lost charger',
  'Emergency nap',
  'Smart broom',
  'Cursed cookie',
  'Talking mirror',
  'Panic pancake',
  'Fancy trash',
  'Invisible problem',
  'Wrong suitcase',
  'Angry calendar',
  'Snack thief',
  'Lazy ninja',
  'Crying printer',
  'Haunted elevator',
  'Secret dance',
  'Fake moustache',
  'Confused teacher',
  'Broken joke',
  'Spicy mistake',
  'Mystery button',
  'Tiny thunder',
  'Drama spoon',
  'Late wizard',
  'Random goat',
  'Screaming kettle',
  'Lucky mistake',
  'Guilty cat',
  'Unstable chair',
  'Forbidden selfie',
  'Dancing potato',
  'Secret boss',
];

export const FRIEND_PHRASES: FriendPhrase[] = PHRASE_TEXTS.map(
  (text, index) => ({
    id: `phrase-${index}`,
    text,
    color: COLORS[index % COLORS.length],
  }),
);
